import React from 'react';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import './globals.css';
import { ConfigProvider } from 'antd';
import AuthProvider from '@/components/providers/AuthProvider';
import theme from '@/theme/themeConfig';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
    <ConfigProvider
        theme={theme}
      >
        <AuthProvider>
      <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </AuthProvider>
      </ConfigProvider>
    </body>
  </html>
);

export default RootLayout;