import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/providers/AuthProvider";
import theme from "@/theme/themeConfig";
import { ConfigProvider } from "antd";
import React from "react";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import "./globals.css";

export const metadata = {
  title: "Cowork",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body>
      <ConfigProvider theme={theme}>
        <AuthProvider>
          <StyledComponentsRegistry>
            <Navbar />

            {children}
          </StyledComponentsRegistry>
        </AuthProvider>
      </ConfigProvider>
    </body>
  </html>
);

export default RootLayout;
